# Generated by Django 5.0.3 on 2024-10-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_position', models.CharField(max_length=100)),
                ('employee_place', models.CharField(max_length=100, null=True)),
                ('employee_age', models.CharField(max_length=100)),
            ],
        ),
    ]
